// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdKdSG_wt_7NEuBYA7XBNu5pmzpKWIxXk',
    appId: '1:5721565384:web:07f204ed2e444c3dfa1dfd',
    messagingSenderId: '5721565384',
    projectId: 'store-app-1c336',
    authDomain: 'store-app-1c336.firebaseapp.com',
    storageBucket: 'store-app-1c336.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqc-7WsO04HO7arYSsjwQiS-66JOq4M0A',
    appId: '1:5721565384:android:246c076ff211792bfa1dfd',
    messagingSenderId: '5721565384',
    projectId: 'store-app-1c336',
    storageBucket: 'store-app-1c336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-Z9O6uETPZqPcrccyp17MR-6P9sg50s',
    appId: '1:5721565384:ios:0ac648034ecec0a0fa1dfd',
    messagingSenderId: '5721565384',
    projectId: 'store-app-1c336',
    storageBucket: 'store-app-1c336.appspot.com',
    iosClientId: '5721565384-ufesvglhpq617bm4jbbs1bo9h3ocd1sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-Z9O6uETPZqPcrccyp17MR-6P9sg50s',
    appId: '1:5721565384:ios:efb65bb7b43556fafa1dfd',
    messagingSenderId: '5721565384',
    projectId: 'store-app-1c336',
    storageBucket: 'store-app-1c336.appspot.com',
    iosClientId: '5721565384-smt5505ia4tg9473o0cu4n0rt1hl4mj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
